import { Home, Users, Stethoscope, Bath, UtensilsCrossed, Wrench, Sparkles, ShieldCheck, Activity, Settings, Heart } from "lucide-react"
import type { LucideIcon } from "lucide-react"

export interface ServiceItem {
  id: number
  image: string
  name: string
  desc: string
  price: string
  unit: string
  rating: number
  sold: number
  tags?: string[]
}

export interface ServiceCategory {
  id: string
  label: string
  icon: LucideIcon
  color: string
  services: ServiceItem[]
}

export const serviceCategories: Record<string, ServiceCategory> = {
  home: {
    id: "home",
    label: "居家护工",
    icon: Home,
    color: "#4DD8CD",
    services: [
      {
        id: 1,
        image: "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=400&h=400&fit=crop",
        name: "24小时专业陪护",
        desc: "提供全天候专业护理服务，包含生活照料、健康监测、用药提醒等",
        price: "¥280",
        unit: "天",
        rating: 4.9,
        sold: 528,
        tags: ["持证上岗", "24小时", "专业护理"],
      },
      {
        id: 2,
        image: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=400&h=400&fit=crop",
        name: "日间照护服务",
        desc: "白天专人照护，协助日常起居、陪同外出、健康管理",
        price: "¥180",
        unit: "天",
        rating: 4.8,
        sold: 326,
        tags: ["日间服务", "灵活预约"],
      },
      {
        id: 3,
        image: "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=400&h=400&fit=crop",
        name: "夜间陪护服务",
        desc: "夜间专人值守，确保老人安全，及时处理突发情况",
        price: "¥150",
        unit: "夜",
        rating: 4.7,
        sold: 215,
        tags: ["夜间服务", "安全保障"],
      },
    ],
  },
  hospital: {
    id: "hospital",
    label: "住院陪护",
    icon: Users,
    color: "#f59e0b",
    services: [
      {
        id: 1,
        image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=400&fit=crop",
        name: "医院24小时陪护",
        desc: "专业护工医院全天陪护，协助护理、送餐、陪检查等",
        price: "¥320",
        unit: "天",
        rating: 4.9,
        sold: 892,
        tags: ["医院陪护", "24小时", "专业护理"],
      },
      {
        id: 2,
        image: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&h=400&fit=crop",
        name: "术后康复陪护",
        desc: "术后专业护理，伤口护理、康复训练指导、营养膳食",
        price: "¥350",
        unit: "天",
        rating: 4.8,
        sold: 456,
        tags: ["术后护理", "康复指导"],
      },
      {
        id: 3,
        image: "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=400&h=400&fit=crop",
        name: "ICU探视陪护",
        desc: "ICU探视期间专业陪同，情绪安抚、医患沟通协助",
        price: "¥200",
        unit: "次",
        rating: 4.9,
        sold: 178,
        tags: ["ICU陪护", "专业沟通"],
      },
    ],
  },
  medical: {
    id: "medical",
    label: "助医服务",
    icon: Stethoscope,
    color: "#ef4444",
    services: [
      {
        id: 1,
        image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=400&fit=crop",
        name: "陪同就医服务",
        desc: "全程陪同挂号、就诊、取药，代为排队，省心省力",
        price: "¥150",
        unit: "次",
        rating: 4.8,
        sold: 1256,
        tags: ["陪同就医", "代排队"],
      },
      {
        id: 2,
        image: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&h=400&fit=crop",
        name: "上门打针换药",
        desc: "持证护士上门，打针、换药、拆线等基础护理",
        price: "¥80",
        unit: "次",
        rating: 4.9,
        sold: 2135,
        tags: ["上门服务", "持证护士"],
      },
      {
        id: 3,
        image: "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=400&h=400&fit=crop",
        name: "代取药/代问诊",
        desc: "代为挂号问诊、取药送药，方便行动不便老人",
        price: "¥50",
        unit: "次",
        rating: 4.7,
        sold: 896,
        tags: ["代取药", "送药上门"],
      },
    ],
  },
  bath: {
    id: "bath",
    label: "助浴服务",
    icon: Bath,
    color: "#8b5cf6",
    services: [
      {
        id: 1,
        image: "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=400&h=400&fit=crop",
        name: "上门助浴服务",
        desc: "专业助浴师上门，携带便携设备，安全舒适助浴",
        price: "¥200",
        unit: "次",
        rating: 4.9,
        sold: 756,
        tags: ["上门服务", "专业设备", "安全助浴"],
      },
      {
        id: 2,
        image: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=400&h=400&fit=crop",
        name: "卧床老人擦浴",
        desc: "专业擦浴服务，适合卧床老人，温和清洁护理",
        price: "¥120",
        unit: "次",
        rating: 4.8,
        sold: 423,
        tags: ["卧床护理", "温和清洁"],
      },
      {
        id: 3,
        image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=400&fit=crop",
        name: "助浴+理发套餐",
        desc: "助浴服务加专业理发，一站式个人清洁护理",
        price: "¥280",
        unit: "次",
        rating: 4.9,
        sold: 312,
        tags: ["套餐服务", "理发"],
      },
    ],
  },
  meal: {
    id: "meal",
    label: "助餐服务",
    icon: UtensilsCrossed,
    color: "#ec4899",
    services: [
      {
        id: 1,
        image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=400&fit=crop",
        name: "营养餐配送",
        desc: "每日新鲜烹制，营养均衡，送餐上门",
        price: "¥35",
        unit: "餐",
        rating: 4.8,
        sold: 3256,
        tags: ["送餐上门", "营养均衡"],
      },
      {
        id: 2,
        image: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400&h=400&fit=crop",
        name: "糖尿病专用餐",
        desc: "低糖低盐，专为糖尿病老人定制的健康餐食",
        price: "¥45",
        unit: "餐",
        rating: 4.9,
        sold: 1256,
        tags: ["低糖低盐", "专病定制"],
      },
      {
        id: 3,
        image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&h=400&fit=crop",
        name: "软食/流食套餐",
        desc: "适合咀嚼困难老人，营养丰富易消化",
        price: "¥40",
        unit: "餐",
        rating: 4.7,
        sold: 856,
        tags: ["软食流食", "易消化"],
      },
    ],
  },
  equipment: {
    id: "equipment",
    label: "器材租售",
    icon: Wrench,
    color: "#3b82f6",
    services: [
      {
        id: 1,
        image: "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=400&h=400&fit=crop",
        name: "轮椅租赁",
        desc: "多款轮椅可选，按天/月租赁，送货上门",
        price: "¥15",
        unit: "天",
        rating: 4.8,
        sold: 1523,
        tags: ["租赁", "送货上门"],
      },
      {
        id: 2,
        image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=400&fit=crop",
        name: "护理床租赁",
        desc: "电动护理床，可调节角度，带护栏防摔",
        price: "¥50",
        unit: "天",
        rating: 4.9,
        sold: 756,
        tags: ["电动调节", "安全护栏"],
      },
      {
        id: 3,
        image: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&h=400&fit=crop",
        name: "制氧机租售",
        desc: "家用制氧机，可租可买，专业安装调试",
        price: "¥30",
        unit: "天",
        rating: 4.8,
        sold: 423,
        tags: ["可租可买", "专业安装"],
      },
    ],
  },
  cleaning: {
    id: "cleaning",
    label: "保洁服务",
    icon: Sparkles,
    color: "#10b981",
    services: [
      {
        id: 1,
        image: "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=400&h=400&fit=crop",
        name: "日常保洁服务",
        desc: "专业保洁人员上门，房间清洁、整理收纳",
        price: "¥120",
        unit: "次",
        rating: 4.8,
        sold: 2356,
        tags: ["上门服务", "专业清洁"],
      },
      {
        id: 2,
        image: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=400&h=400&fit=crop",
        name: "深度清洁服务",
        desc: "厨房、卫生间深度清洁，去污除菌",
        price: "¥280",
        unit: "次",
        rating: 4.9,
        sold: 1256,
        tags: ["深度清洁", "除菌消毒"],
      },
      {
        id: 3,
        image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=400&fit=crop",
        name: "定期保洁套餐",
        desc: "每周固定保洁，长期服务更优惠",
        price: "¥400",
        unit: "月",
        rating: 4.8,
        sold: 856,
        tags: ["长期服务", "优惠套餐"],
      },
    ],
  },
  safety: {
    id: "safety",
    label: "安全检查",
    icon: ShieldCheck,
    color: "#f97316",
    services: [
      {
        id: 1,
        image: "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=400&h=400&fit=crop",
        name: "居家安全评估",
        desc: "专业人员上门评估居家环境安全隐患",
        price: "¥200",
        unit: "次",
        rating: 4.9,
        sold: 523,
        tags: ["上门评估", "专业报告"],
      },
      {
        id: 2,
        image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=400&fit=crop",
        name: "智能安防安装",
        desc: "烟感、燃气报警、紧急呼叫等设备安装",
        price: "¥500",
        unit: "套",
        rating: 4.8,
        sold: 312,
        tags: ["智能设备", "专业安装"],
      },
      {
        id: 3,
        image: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&h=400&fit=crop",
        name: "定期安全巡查",
        desc: "每周上门检查水电气安全，排除隐患",
        price: "¥150",
        unit: "月",
        rating: 4.7,
        sold: 186,
        tags: ["定期服务", "隐患排查"],
      },
    ],
  },
  health: {
    id: "health",
    label: "慢病监测",
    icon: Activity,
    color: "#06b6d4",
    services: [
      {
        id: 1,
        image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=400&fit=crop",
        name: "血压血糖监测",
        desc: "护士上门测量血压血糖，建立健康档案",
        price: "¥50",
        unit: "次",
        rating: 4.9,
        sold: 2356,
        tags: ["上门服务", "建档跟踪"],
      },
      {
        id: 2,
        image: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&h=400&fit=crop",
        name: "慢病管理套餐",
        desc: "定期监测+用药指导+饮食建议，全方位管理",
        price: "¥300",
        unit: "月",
        rating: 4.8,
        sold: 856,
        tags: ["全方位管理", "专业指导"],
      },
      {
        id: 3,
        image: "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=400&h=400&fit=crop",
        name: "远程健康监测",
        desc: "智能设备24小时监测，异常自动预警",
        price: "¥200",
        unit: "月",
        rating: 4.8,
        sold: 523,
        tags: ["24小时监测", "智能预警"],
      },
    ],
  },
  renovation: {
    id: "renovation",
    label: "适老改造",
    icon: Settings,
    color: "#6366f1",
    services: [
      {
        id: 1,
        image: "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=400&h=400&fit=crop",
        name: "卫生间适老改造",
        desc: "安装扶手、防滑地砖、坐便椅等适老设施",
        price: "¥2000",
        unit: "套",
        rating: 4.9,
        sold: 356,
        tags: ["安全改造", "防滑扶手"],
      },
      {
        id: 2,
        image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=400&fit=crop",
        name: "无障碍通道改造",
        desc: "门槛坡道、通道拓宽，方便轮椅通行",
        price: "¥3000",
        unit: "套",
        rating: 4.8,
        sold: 186,
        tags: ["无障碍", "轮椅通行"],
      },
      {
        id: 3,
        image: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&h=400&fit=crop",
        name: "全屋适老评估改造",
        desc: "专业评估+设计方案+全屋改造一站式服务",
        price: "¥8000",
        unit: "套",
        rating: 4.9,
        sold: 98,
        tags: ["一站式", "专业设计"],
      },
    ],
  },
  warm: {
    id: "warm",
    label: "暖心服务",
    icon: Heart,
    color: "#f43f5e",
    services: [
      {
        id: 1,
        image: "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=400&h=400&fit=crop",
        name: "陪伴聊天服务",
        desc: "温馨陪伴，倾听心声，缓解孤独感",
        price: "¥80",
        unit: "小时",
        rating: 4.9,
        sold: 1256,
        tags: ["温馨陪伴", "心理慰藉"],
      },
      {
        id: 2,
        image: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=400&h=400&fit=crop",
        name: "代购跑腿服务",
        desc: "代购日用品、药品，跑腿办事",
        price: "¥30",
        unit: "次",
        rating: 4.8,
        sold: 2356,
        tags: ["代购", "跑腿"],
      },
      {
        id: 3,
        image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=400&fit=crop",
        name: "节日关怀服务",
        desc: "节日上门探望，送温暖送祝福",
        price: "¥100",
        unit: "次",
        rating: 4.9,
        sold: 523,
        tags: ["节日关怀", "送温暖"],
      },
    ],
  },
}

export const getServiceCategory = (id: string): ServiceCategory | undefined => {
  return serviceCategories[id]
}
